export const FieldLength = {
    TASK_SUBJECT: 45,
    TASK_DESCRIPTION: 255,

    USER_MAX_EMAIL: 50,
    USER_MIN_PASSWORD: 5,
    USER_MAX_PASSWORD: 20,
    USER_MAX_NAME: 25,
    USER_MAX_SURNAME: 25,
    USER_MAX_PATRONYMIC: 25,
    USER_MIN_BIRTHDATE: 10,
    USER_MAX_BIRTHDATE: 10,

    COMMENT_TEXT: 255,
};
