CREATE TABLE IF NOT EXISTS usr_role(
    usr_id BIGINT,
    role_id BIGINT,
    FOREIGN KEY (usr_id) REFERENCES usr(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES role(id) ON UPDATE RESTRICT ON DELETE CASCADE
);
