application:
    name: Tasker
    version: 1.0.1-SNAPSHOT

spring:
    datasource:
        url: jdbc:postgresql://localhost:5444/tasklist
        username: postgres
        password: IamRoot

    jpa:
        generate-ddl: false
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true

    liquibase:
        change-log: classpath:/db/changelog/master.xml

    mail:
        default-encoding: UTF-8
        port: 465
        protocol: smtps
        username: mnopqwaszx@gmail.com
        password: qwerty12345A
        host: smtp.gmail.com
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true


logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type.descriptor.sql.BasicBinder: TRACE


security:
        jwt:
            key: secret
            token.expiredIn: 7200000
